import { StyleSheet } from "react-native";
import { COLORS, SPACING, BORDER_RADIUS } from "./theme";

export const globalStyles = StyleSheet.create({
  authSafeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  authScroll: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xxl,
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    padding: SPACING.xxl,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screenContent: {
    padding: SPACING.lg,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: SPACING.xs,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textSub,
    marginBottom: SPACING.xl,
    textAlign: "center",
  },
  inputWrap: {
    marginBottom: SPACING.sm,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.inputLabel,
    marginBottom: SPACING.sm,
    marginLeft: 2,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    borderRadius: BORDER_RADIUS.md,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    color: COLORS.inputText,
  },
  timePickerField: {
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    borderRadius: BORDER_RADIUS.md,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  timePickerValue: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.inputText,
  },
  timePickerPanel: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    borderRadius: BORDER_RADIUS.xl,
    backgroundColor: "#f8fbff",
    overflow: "hidden",
  },
  timePickerDoneButton: {
    alignSelf: "flex-end",
    marginRight: SPACING.md,
    marginBottom: SPACING.md,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#dbe5ff",
  },
  timePickerDoneText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    shadowColor: "#3d57a0",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  sectionCard: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textSub,
  },
  sectionLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: SPACING.sm,
  },
  profileHeroCard: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    padding: SPACING.xl,
    marginBottom: SPACING.lg,
    gap: SPACING.md,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  profileHeroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  profileName: {
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 4,
  },
  profileEmail: {
    fontSize: 14,
    color: COLORS.textSub,
  },
  roleBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: 1,
  },
  roleBadgeAdmin: {
    backgroundColor: "#f3e8ff",
    borderColor: "#d8b4fe",
  },
  roleBadgeUser: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  roleBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
  },
  roleBadgeTextAdmin: {
    color: "#7c3aed",
  },
  inlinePillAction: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#cdd9ff",
  },
  inlinePillActionText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
  },
  buttonBase: {
    borderRadius: BORDER_RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#203a86",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  buttonPrimary: {
    backgroundColor: COLORS.primary,
  },
  buttonSecondary: {
    backgroundColor: COLORS.secondary,
    borderWidth: 1,
    borderColor: "#cdd9ff",
  },
  buttonDanger: {
    backgroundColor: COLORS.danger,
  },
  buttonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "600",
  },
  buttonTextPrimary: {
    color: COLORS.white,
  },
  buttonTextSecondary: {
    color: "#334a8a",
  },
  buttonRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  halfButton: {
    flex: 1,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2ff",
  },
  detailLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.inputLabel,
  },
  detailValue: {
    flex: 1,
    fontSize: 14,
    color: COLORS.inputText,
    textAlign: "right",
    fontWeight: "600",
  },
  preferenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  preferenceHint: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.textSub,
    marginTop: 4,
  },
  segmentedContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.inputBorder,
    borderRadius: 10,
    padding: 2,
    marginBottom: SPACING.md,
  },
  segmentedItem: {
    flex: 1,
    paddingVertical: SPACING.sm,
    alignItems: "center",
    borderRadius: BORDER_RADIUS.md,
  },
  segmentedItemActive: {
    backgroundColor: COLORS.white,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  segmentedText: {
    fontSize: 13,
    color: COLORS.textSub,
    fontWeight: "600",
  },
  segmentedTextActive: {
    color: COLORS.primary,
  },
  miniChartCard: {
    width: "100%",
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    padding: SPACING.lg,
    marginBottom: SPACING.xs,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    borderWidth: 1,
    borderColor: "#eef2ff",
  },
  miniChartHeader: {
    marginBottom: SPACING.xs,
  },
  todayIndicator: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 2,
  },
  todayValue: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textHeader,
  },
  todayUnit: {
    fontSize: 10,
    color: COLORS.textMuted,
    marginLeft: 2,
    fontWeight: "600",
  },
  chartSectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 10,
    marginLeft: 4,
  },
  riskSummaryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  riskLevelBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: 1,
  },
  riskLevelText: {
    fontSize: 12,
    fontWeight: "700",
  },
  riskScoreRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
    marginTop: SPACING.md,
  },
  riskScoreValue: {
    fontSize: 30,
    fontWeight: "800",
    color: COLORS.textHeader,
    lineHeight: 34,
  },
  riskScoreUnit: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.textMuted,
    marginBottom: 4,
  },
  riskSignalsList: {
    gap: SPACING.xs,
    marginTop: SPACING.md,
  },
  riskSignalRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  riskSignalBullet: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  riskSignalText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textSub,
  },
  riskSignalEmpty: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textSub,
    fontStyle: "italic",
  },
  weeklyTextCard: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: "#e4ebff",
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  weeklyTextRow: {
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2ff",
  },
  weeklyTextDayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: 4,
  },
  weeklyTextDay: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4d6090",
  },
  weeklyTextTodayBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "#e0e7ff",
    color: COLORS.primary,
    fontSize: 10,
    fontWeight: "700",
  },
  weeklyTextBody: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textSub,
  },
  weeklyTextMuted: {
    color: COLORS.textMuted,
    fontStyle: "italic",
  },
  chip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    backgroundColor: "#f1f5f9",
    marginRight: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontSize: 13,
    color: COLORS.textSub,
    fontWeight: "600",
  },
  chipTextActive: {
    color: COLORS.white,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  statCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: "#f8fbff",
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    padding: SPACING.md,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSub,
    fontWeight: "600",
  },
  listItemHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.sm,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 2,
  },
  cardMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textSub,
  },
  reminderTimeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#dbe5ff",
  },
  reminderTimeText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
  },
  reminderCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.sm,
  },
  reminderCardBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  reminderDeleteIconAction: {
    paddingVertical: 2,
    paddingHorizontal: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateText: {
    fontSize: 13,
    lineHeight: 20,
    color: COLORS.textSub,
  },
  loadingText: {
    fontSize: 13,
    color: COLORS.textSub,
    textAlign: "center",
    marginTop: SPACING.sm,
  },
});
