import { StyleSheet, Platform } from "react-native";
import { COLORS, SPACING, BORDER_RADIUS } from "./theme";

export const globalStyles = StyleSheet.create({
  authSafeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  authScroll: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xxl,
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    borderWidth: 1,
    borderColor: "#dbe5ff",
    padding: SPACING.xxl,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screenContent: {
    padding: SPACING.lg,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: SPACING.xs,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textSub,
    marginBottom: SPACING.xl,
    textAlign: "center",
  },
  inputWrap: {
    marginBottom: SPACING.sm,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.inputLabel,
    marginBottom: SPACING.sm,
    marginLeft: 2,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    borderRadius: BORDER_RADIUS.md,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    color: COLORS.inputText,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    shadowColor: "#3d57a0",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  buttonBase: {
    borderRadius: BORDER_RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#203a86",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  buttonPrimary: {
    backgroundColor: COLORS.primary,
  },
  buttonSecondary: {
    backgroundColor: COLORS.secondary,
    borderWidth: 1,
    borderColor: "#cdd9ff",
  },
  buttonDanger: {
    backgroundColor: COLORS.danger,
  },
  buttonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "600",
  },
  buttonTextPrimary: {
    color: COLORS.white,
  },
  buttonTextSecondary: {
    color: "#334a8a",
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  segmentedContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.inputBorder,
    borderRadius: 10,
    padding: 2,
    marginBottom: SPACING.md,
  },
  segmentedItem: {
    flex: 1,
    paddingVertical: SPACING.sm,
    alignItems: "center",
    borderRadius: BORDER_RADIUS.md,
  },
  segmentedItemActive: {
    backgroundColor: COLORS.white,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  segmentedText: {
    fontSize: 13,
    color: COLORS.textSub,
    fontWeight: "600",
  },
  segmentedTextActive: {
    color: COLORS.primary,
  },
  miniChartCard: {
    width: "100%",
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    padding: SPACING.lg,
    marginBottom: SPACING.xs,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    borderWidth: 1,
    borderColor: "#eef2ff",
  },
  miniChartHeader: {
    marginBottom: SPACING.xs,
  },
  todayIndicator: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 2,
  },
  todayValue: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textHeader,
  },
  todayUnit: {
    fontSize: 10,
    color: COLORS.textMuted,
    marginLeft: 2,
    fontWeight: "600",
  },
  chartSectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textHeader,
    marginBottom: 10,
    marginLeft: 4,
  },
  weeklyTextCard: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xxl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: "#e4ebff",
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  weeklyTextRow: {
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2ff",
  },
  weeklyTextDayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: 4,
  },
  weeklyTextDay: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4d6090",
  },
  weeklyTextTodayBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "#e0e7ff",
    color: COLORS.primary,
    fontSize: 10,
    fontWeight: "700",
  },
  weeklyTextBody: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textSub,
  },
  weeklyTextMuted: {
    color: COLORS.textMuted,
    fontStyle: "italic",
  },
  chip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    backgroundColor: "#f1f5f9",
    marginRight: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontSize: 13,
    color: COLORS.textSub,
    fontWeight: "600",
  },
  chipTextActive: {
    color: COLORS.white,
  },
  statusCard: {
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 1,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
  },
  statusCardInfo: {
    backgroundColor: "#f8fbff",
    borderColor: "#d9ebff",
  },
  statusCardSuccess: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  statusCardWarning: {
    backgroundColor: "#fffbeb",
    borderColor: "#fcd34d",
  },
  statusCardDanger: {
    backgroundColor: "#fff1f2",
    borderColor: "#fecdd3",
  },
  statusHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
    gap: SPACING.sm,
  },
  statusTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textHeader,
  },
  statusMeta: {
    fontSize: 12,
    color: COLORS.textSub,
  },
  statusBody: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textSub,
    marginBottom: SPACING.md,
  },
});
